name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build-essential
      run: sudo apt-get install build-essential

    - name: Cache build output
      uses: actions/cache@v3
      with:
        path: ./myfind
        key: ${{ runner.os }}-myfind-${{ github.sha }}
  
    - name: Build with Makefile
      run: make all

