name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build-essential
      run: sudo apt-get install build-essential
  
    - name: Build with Makefile
      run: make all
      
    - name: Upload myfind executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: myfind-executable
        path: ./myfind
